### ISSUE TITLE
Shard selection based on business id

### ISSUE THREAD

**Issue by grahambunce** [darioquintana/NHibernate-Shards#3]
Hi,

I’m trying work out if there is a sharding strategy based on business key (customer id). I can see the round robin example but that doesn’t seem appropriate.

We are working with tenanted data.... so all entities in a session will belong to the same shard.... so conceptually when we create a session we want to say ‘create a session for customer X’ and the sharding framework will either know that X relates to shard Y or that X isn’t in a shard so it will assign one.

Is this available out of the box and I’ve missed it in the code?

Thanks

**Comment by ggeurts** [comment]
You can implement a custom IShardSelectionStrategy to achieve the desired effect.

**Comment by grahambunce** [comment]
Thanks.... I thought you’d probably say that.... we have a loose collection of objects rather the classic aggregate root but I may be able to work around this.

The next concern I have is with queries ..... I can see two access strategies.... sequential and parallel but these both access all shards. In my case I know the customer up front and want to ensure that the query only runs in the appropriate shard. 

We use linq a lot..... and I think we need to somehow interrogate the query to see which customer you are using via a custom access strategy..... I thought maybe the shard operation would help, and then I noticed this comment 

> implies that the establishing of shard-specific sessions, queries and/or criterias must be done before the delegate is returned by this method

How would you recommended establishing the specific shard with a linq query?

**Comment by ggeurts** [comment]
It is possible to open a session for a limited number of shards using IShardedSessionFactory. When only a single shardid is specified the unshared NHibernate session is used without any sharding overhead. So if the customer shard is known early on, this is the easiest and most performant way to go.

**Comment by grahambunce** [comment]
Ok, so I think you’re saying use the session factory (which is per shard anyway) to open the factory for the correct shard... then use the session as normal. Ok, that makes sense.

I presume this also means I am responsible for mapping the customer to the shard outside of nhibernate shards....because then I know customer X uses shard Y so I should open shard Y myself? 

Btw Does this impact use of sharded Hilo generator do I not really need to worry too much about the rest of the sharding framework in my scenario?

**Comment by ggeurts** [comment]
You would indeed be responsible for the customer => shardid mapping. If that mapping information is derived from data stored in the shards itself, you could use a sharded query to gather this information and cache its results for future use. Other than that, there shouldn't be any reason to access shards directly.

As long as the sharded HiLo generator is initalized correctly with a control session provider, it can be used safely.

**Comment by grahambunce** [comment]
@ggeurts  Can I just check - is the Strategy Factory irrelevant in my scenario? I've copied this from the unit tests but I'm not sure what to replace it with. I can't send null to the ShardedConfiguration class which is where I'm setting everything up.

I'm not sure what to replace it with if none of this logic is going be invoked since I'm just opening a session factory for a shard and using that as if it was a normal session.

```
		private class StrategyFactory : IShardStrategyFactory
		{
			public IShardStrategy NewShardStrategy(IEnumerable<ShardId> shardIds)
			{
				var loadBalancer = new RoundRobinShardLoadBalancer(shardIds);
				return new ShardStrategyImpl(
					new RoundRobinShardSelectionStrategy(loadBalancer),
					new AllShardsShardResolutionStrategy(shardIds),
					new ParallelShardAccessStrategy());
			}
		}
```

**Comment by grahambunce** [comment]
@ggeurts sorry... one other question... In the standard NHibernate session I can get the current DbConnection from the session Connection property. In Shards this property is Not Implemented... I guess it's because a sharded session can handle mutiple database connections as handled by the establishedSessionsByShard variable in ShardedSessionImpl.

In my case though it's a simple tenanted sharding setup. As suggested, I'm getting the appropriate session factory for the shard I want to use for the particular tenant, and then opening a session from that session factory.

Understandably, this is opening a ShardedSession, not a standard session... but this Sharded session (should?) only ever have one DbConnection.

is there a way i can get this connection from somewhere? the session factory will not expose it so unless the Session can find a way to do so it appears to be hidden in the internals.
