### ISSUE TITLE
Sharding does not implement Future Queries

### ISSUE THREAD

**Issue by grahambunce** [darioquintana/NHibernate-Shards#4]
I'm converting my sessions to use sharded sessions based on a tenant model (explictly open a session factory and then the session from that). My future queries are throwing an error:

NHibernate.Shards.Session.ShardedSessionImpl+DelegatingSessionImpl requires to implement NHibernate.Impl.AbstractSessionImpl class to support future batch

Are there any plans to implement Future batch queries? I appreciate that it's not really appropriate for cross-shard queries but the shard-per-tenant model is common and there is nothing to stop future queries in that scenario. 

My alternative is to get a *real* session instead...

I can see that the IShardedSession api has a "GetSessionForObject" that returns an ISession (but at this stage I don't have an associated object to use) and the ShardedSessionImpl class has a private AnySession (but not exposed) and an EstablishFor(IShard shard) method but the only way I can see to get a shard is to use the ShardedSessionImpl Shards property - knowing that I only have the one shard.

Can any of these methods be exposed via the interface? (e.g the EstablishFor and Shard method/property?)

Is there a better way to do this?

**Comment by ggeurts** [comment]
Hi Graham, would be able to post a repro of the problem?

**Comment by grahambunce** [comment]
I’m not sure there is a need.... I worked around it by casting to the concrete sharded session impel and then used that to build a real session. I could do that as I knew what shard I was operating on so effectively I rarely use the sharded session except for one or two small use cases where it’s appropriate. Therefore I have a real session so future queries work ok off that.

I guess I was trying to avoid the cast to the concrete type to be able to wire this us but that’s not essential I guess.

Apart from that; it’s all working well so thanks for maintaining this over the past few years

**Comment by ggeurts** [comment]
For your purpose it seems to make sense to offer a IShardedSession.LockShard(ShardId) overload that forces all subsequent session operations to be locked to the given shard.

**Comment by grahambunce** [comment]
I agree, the equivalent of GetSessionForObject but for a known shard Id would be more consistent to the current api than the hoops I’m jumping through to do the same thing.

**Comment by ggeurts** [comment]
Solved with commit 59e4a3d2898cfe11b85d23176a89da9339bd9233.
